apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: noderefreshes.noderefresh.io
spec:
  group: noderefresh.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNodeLabels:
                  type: object
                  description: "Labels to identify target nodes for refresh"
                  additionalProperties:
                    type: string
                maxPodsToMoveAtOnce:
                  type: integer
                  minimum: 1
                  default: 5
                  description: "Maximum number of pods to move concurrently"
                minHealthThreshold:
                  type: integer
                  minimum: 0
                  maximum: 100
                  default: 80
                  description: "Minimum percentage of healthy pods before proceeding"
                refreshSchedule:
                  type: string
                  description: "Cron expression for automated refresh (e.g., '0 0 */3 * *')"
                  pattern: '^(\*|([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])|\*\/([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])) (\*|([0-9]|1[0-9]|2[0-3])|\*\/([0-9]|1[0-9]|2[0-3])) (\*|([1-9]|1[0-9]|2[0-9]|3[0-1])|\*\/([1-9]|1[0-9]|2[0-9]|3[0-1])) (\*|([1-9]|1[0-2])|\*\/([1-9]|1[0-2])) (\*|([0-6])|\*\/([0-6]))$'
                gracePeriodSeconds:
                  type: integer
                  minimum: 0
                  default: 300
                  description: "Grace period for pod termination"
                nodeProvisionTimeout:
                  type: integer
                  minimum: 60
                  default: 600
                  description: "Timeout in seconds for new node provisioning"
              required:
                - targetNodeLabels
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Idle
                    - Provisioning
                    - Draining
                    - Validating
                    - Completed
                    - Failed
                lastRefreshTime:
                  type: string
                  format: date-time
                nextRefreshTime:
                  type: string
                  format: date-time
                currentNode:
                  type: string
                  description: "Node currently being refreshed"
                nodesRefreshed:
                  type: array
                  items:
                    type: string
                totalNodes:
                  type: integer
                podsMovedSuccessfully:
                  type: integer
                podsMovesFailed:
                  type: integer
                message:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Current Node
          type: string
          jsonPath: .status.currentNode
        - name: Nodes Refreshed
          type: integer
          jsonPath: .status.nodesRefreshed
        - name: Total Nodes
          type: integer
          jsonPath: .status.totalNodes
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: noderefreshes
    singular: noderefresh
    kind: NodeRefresh
    shortNames:
      - nr
